### ISSUE TITLE
Client is not dissconected after closing alient app using Ctrl+C

### ISSUE THREAD

**Issue by roman-dudko** [roman-dudko/console-chat#9]
1. start server
2. connect 2 client end exchange a few messages
3. close one client using Ctrl+C
4. send message as 2nd client

Observed:
Server tries to broadcast message to disconnected client and rises exception.

**Comment by roman-dudko** [comment]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/pythonCourses/console-chat/server.py", line 26, in listen_client
    broadcast(message)
  File "/home/ubuntu/pythonCourses/console-chat/server.py", line 19, in broadcast
    client.send(message)
BrokenPipeError: [Errno 32] Broken pipe
